version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["94:73:c0:34:7d:22:1d:89:cd:61:4f:ab:79:e1:40:2b"]
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: ansible-playbook -i inventory main-remote.yml

  smoke_test:
    docker:
      - image: alpine:3.15
    steps:
      - run: apk add --update curl
      - checkout
      - run:
          name: smoke test
          command: |
            export IP=$(tail -n 1 inventory)
            export response=$(curl $IP:3000)
            if [ $response != 'Hello worl!' ]; then
              return 1
            fi

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
      - smoke_test
